### ISSUE TITLE
An error while using DNS provider as alidns and a requirement for using an enviroment-variable to make wildcard certificate.

### ISSUE THREAD

**Issue by dgautumn** [rawmind0/alpine-traefik#118]
1. I am setting DNS provider to alidns, but there is throwing an error at first. This error i was solved and tested by add the package "tzdata". The docker image version is 1.7.0-0.

Here is the error imformation:
```
2018/9/28 下午3:12:30time="2018-09-28T07:12:30Z" level=error msg="Error in Go routine: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory"
2018/9/28 下午3:12:30goroutine 594 [running]:
2018/9/28 下午3:12:30runtime/debug.Stack(0x769e27, 0xc0000ba230, 0x25b8557)
2018/9/28 下午3:12:30	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018/9/28 下午3:12:30runtime/debug.PrintStack()
2018/9/28 下午3:12:30	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
2018/9/28 下午3:12:30github.com/containous/traefik/safe.defaultRecoverGoroutine(0x20eeba0, 0xc0000581d0)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/safe/routine.go:148 +0x85
2018/9/28 下午3:12:30github.com/containous/traefik/safe.GoWithRecover.func1.1(0x26652b8)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/safe/routine.go:139 +0x57
2018/9/28 下午3:12:30panic(0x20eeba0, 0xc0000581d0)
2018/9/28 下午3:12:30	/usr/local/go/src/runtime/panic.go:513 +0x1b9
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils.GetTimeInFormatISO8601(0x20d2640, 0xc0003f98f0)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/utils/utils.go:60 +0x140
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.completeRpcSignParams(0x28e0ce0, 0xc0001fe310, 0x28c39c0, 0xc00000cd60, 0x259f41d, 0xb, 0x0, 0x0)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/rpc_signature_composer.go:47 +0x1de
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.signRpcRequest(0x28e0ce0, 0xc0001fe310, 0x28c39c0, 0xc00000cd60, 0x259f41d, 0xb, 0x28e2480, 0x3)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/rpc_signature_composer.go:26 +0x73
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth.Sign(0x28e0ce0, 0xc0001fe310, 0x28c39c0, 0xc00000cd60, 0x259f41d, 0xb, 0x8, 0x0)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/signer.go:87 +0x273
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.buildHttpRequest(0x28e0ce0, 0xc0001fe310, 0x28c39c0, 0xc00000cd60, 0x259f41d, 0xb, 0xc0003f9980, 0x0, 0x8)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:287 +0x84
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoActionWithSigner(0xc000685d10, 0x28e0ce0, 0xc0001fe310, 0x28c4560, 0xc00033dc20, 0x0, 0x0, 0x20d2601, 0xc0005cf3c0)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:239 +0x3d2
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk.(*Client).DoAction(0xc000685d10, 0x28e0ce0, 0xc0001fe310, 0x28c4560, 0xc00033dc20, 0xc0003f98f0, 0xc00000c380)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/client.go:151 +0x5b
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns.(*Client).DescribeDomains(0xc000685d10, 0xc0001fe310, 0xf, 0x637d278d58e596b2, 0xb5930e9e99f3b02b)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/alidns/describe_domains.go:27 +0x98
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/alidns.(*DNSProvider).getHostedZone(0xc000770950, 0xc00057b370, 0xf, 0x57, 0xc0005afd00, 0x20, 0xc00050e900, 0x2b, 0x78)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/alidns/alidns.go:153 +0x55
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/alidns.(*DNSProvider).Present(0xc000770950, 0xc00057b370, 0xf, 0xc00050e7b0, 0x2b, 0xc000a3ad80, 0x57, 0x0, 0xc000c0d638)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/providers/dns/alidns/alidns.go:112 +0xba
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*dnsChallenge).PreSolve(0xc00073c000, 0xc0000543f0, 0x6a, 0xc00057b3a8, 0x6, 0xc00057b3b0, 0x7, 0xc00050e7b0, 0x2b, 0x0, ...)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/dns_challenge.go:100 +0x17d
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).solveChallengeForAuthz(0xc00099c000, 0xc000470e40, 0x1, 0x1, 0x0, 0x0)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:601 +0x3c6
2018/9/28 下午3:12:30github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.(*Client).ObtainCertificate(0xc00099c000, 0xc0003bc430, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1, 0x1, ...)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/client.go:434 +0x2b3
2018/9/28 下午3:12:30github.com/containous/traefik/provider/acme.(*Provider).resolveCertificate(0xc00027b200, 0xc000898785, 0xf, 0x0, 0x0, 0x0, 0xc000745f00, 0x0, 0x0, 0x0)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/provider/acme/provider.go:396 +0xabd
2018/9/28 下午3:12:30github.com/containous/traefik/provider/acme.(*Provider).watchNewDomains.func1.1()
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/provider/acme/provider.go:355 +0x6a
2018/9/28 下午3:12:30github.com/containous/traefik/safe.GoWithRecover.func1(0x26652b8, 0xc000313e60)
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
2018/9/28 下午3:12:30created by github.com/containous/traefik/safe.GoWithRecover
2018/9/28 下午3:12:30	/go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
```

2. Is it possible to add an enviroment-variable to make traefik wildcard certificate? Such as the code modified in /root/opt/traefik/bin/traefik.toml.sh below. The enviroment-variable is setting the wildcard main domain and sans, for example *.example.com can set as TRAEFIK_ACME_WILDCARD_DOMAINS=example.com .

`TRAEFIK_ACME_WILDCARD_DOMAINS=${TRAEFIK_ACME_WILDCARD_DOMAINS:-""}`

```
     if [ "${TRAEFIK_ACME_CHALLENGE}" == "dns" ]; then
        TRAEFIK_ACME_CFG=${TRAEFIK_ACME_CFG}"\
  [acme.dnsChallenge]
    provider = \"${TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER}\"
    delayBeforeCheck = ${TRAEFIK_ACME_CHALLENGE_DNS_DELAY}
"

        if [ -n "${TRAEFIK_ACME_WILDCARD_DOMAINS}" ]; then
            IFS=","
            for domain in ${TRAEFIK_ACME_WILDCARD_DOMAINS}; do
                TRAEFIK_ACME_CFG=${TRAEFIK_ACME_CFG}"\
    [[acme.domains]]
      main = \"*.$domain\"
      sans = [\"$domain\"]
"
            done
            unset $IFS
        fi
    fi
```

3. After i install the package "tzdata" and modified the traefik.toml.sh ,it is successfully for wildcard domian certificate. But if there is a normal domain (e.g. aaa.ceshi.example.com, is not useful by wildcard domian), there is an error throwing out:

```
2018/9/28 下午5:13:57time="2018-09-28T09:13:57Z" level=error msg="Unable to obtain ACME certificate for domains \"aaa.****.com\" detected thanks to rule \"Host:aaa.****.com\" : unable to generate a certificate for the domains [aaa.****.com]: acme: Error -> One or more domains had a problem:\n[aaa.****.com] error presenting token: alicloud: unexpected response code 'SERVFAIL' for aaa.****.com.\n"
```

I've checked alicloud operation log , can not find the dns api event in the logs and can not find the reason. So i think maybe we can going on the wildcard domain. 

thanks for your awsome works.

**Comment by dgautumn** [comment]
I found we can use two traefik by sharing the acme folder to use wildcard and normal domain.
